// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADvYoJFxgf8kMfmDQ_7XoxjCiLgFPer9M',
    appId: '1:80026825394:android:2e70fa78201e1f8f218fab',
    messagingSenderId: '80026825394',
    projectId: 'plan-together-e624c',
    storageBucket: 'plan-together-e624c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgL2WgjSqS6xgpgg-iKZXaTsNOobHZEV0',
    appId: '1:80026825394:ios:494498262f297d32218fab',
    messagingSenderId: '80026825394',
    projectId: 'plan-together-e624c',
    storageBucket: 'plan-together-e624c.appspot.com',
    androidClientId: '80026825394-afol1n4as6hli85bha4qbarodb2g387b.apps.googleusercontent.com',
    iosClientId: '80026825394-qhkc23vrdes9td843ki7i2iuefi4i9ku.apps.googleusercontent.com',
    iosBundleId: 'com.plantogether.test',
  );
}
